spring.cloud.stream:
  function:
    definition: produceMessages;consumeMessages
    bindings:
      produceMessages-out-0: kafka-string-output
      consumeMessages-in-0: kafka-string-input
  bindings:
    kafka-string-output:
      destination: ${KAFKA_STRING_TOPIC}
    kafka-string-input:
      destination: ${KAFKA_STRING_TOPIC}
  default-binder: kafka
  kafka:
    binder:
      brokers: ${SERVER}
      auto-create-topics: false