spring.cloud.stream:
  function:
    definition: produceMessages;processMessages;consumeMessages
    bindings:
      produceMessages-out-0: kafka-id
      consumeMessages-in-0: kafka-request
      processMessages-in-0: kafka-id
      processMessages-out-0: kafka-request
  bindings:
    kafka-id:
      destination: ${KAFKA_STRING_TOPIC}
    kafka-request:
      destination: ${KAFKA_POJO_TOPIC}
  default-binder: kafka
  kafka:
    binder:
      brokers: ${SERVER}
      auto-create-topics: false